server:
  port: 8801
spring:
  application:
    name: cloud-stream-privider #端口和微服务名称 老两样

  #中间cloud部分和8802一样
  cloud:
    stream:
      binders:   #自此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment:  # 设置rabbitmq的相关的环境配置 stream3.1只需要配置这些即可
            spring:
              rabbitmq:
                host: localhost
                port: 5672  #mq调用的端口为5672
                username: guest
                password: guest